In [399]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import GridSearchCV

# Train dataset

In [400]:
train = pd.read_csv(r"C:\Users\sreeh\Downloads\train_ctrUa4K.csv")

In [401]:
train

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [402]:
train.shape

(614, 13)

In [403]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [404]:
train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [405]:
train['Credit_History'].mode()

0    1.0
Name: Credit_History, dtype: float64

In [406]:
train['Self_Employed'].mode()

0    No
Name: Self_Employed, dtype: object

In [407]:
train['LoanAmount'].mean()

146.41216216216216

In [408]:
train['Dependents'].mode()

0    0
Name: Dependents, dtype: object

In [409]:
train['Loan_Amount_Term'].mean()

342.0

In [410]:
train['Gender'].mode()

0    Male
Name: Gender, dtype: object

In [411]:
train['Married'].mode()

0    Yes
Name: Married, dtype: object

In [412]:
train['Credit_History'].fillna(1, inplace=True)
train['Self_Employed'].fillna('No', inplace=True)
train['LoanAmount'].fillna(146, inplace=True)
train['Dependents'].fillna('0', inplace=True)
train['Loan_Amount_Term'].fillna(342, inplace=True)
train['Gender'].fillna('Male', inplace=True)
train['Married'].fillna('Yes', inplace=True)

In [413]:
train.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [414]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             614 non-null    object 
 2   Married            614 non-null    object 
 3   Dependents         614 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      614 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [415]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
train['Gender'] = label_encoder.fit_transform(train['Gender'])
train['Gender'].unique()

array([1, 0])

In [416]:
train['Married'] = label_encoder.fit_transform(train['Married'])
train['Married'].unique()

array([0, 1])

In [417]:
train['Dependents'] = label_encoder.fit_transform(train['Dependents'])
train['Dependents'].unique()

array([0, 1, 2, 3])

In [418]:
train['Education'] = label_encoder.fit_transform(train['Education'])
train['Education'].unique()

array([0, 1])

In [419]:
train['Self_Employed'] = label_encoder.fit_transform(train['Self_Employed'])
train['Self_Employed'].unique()

array([0, 1])

In [420]:
train['Property_Area'] = label_encoder.fit_transform(train['Property_Area'])
train['Property_Area'].unique()

array([2, 0, 1])

In [421]:
train['Loan_Status'] = label_encoder.fit_transform(train['Loan_Status'])
train['Loan_Status'].unique()

array([1, 0])

# Test dataset

In [422]:
test=pd.read_csv(r"C:\Users\sreeh\Downloads\test_lAUu6dG.csv")
test

Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area  
0               1.0         Urban  
1               1.0         Urban  
2               1.0         Urban  
3               NaN         Urban  
4               1.0         Urban  
..              ...           ...  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural  

[367 rows x 12 columns]

In [423]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            367 non-null    object 
 1   Gender             356 non-null    object 
 2   Married            367 non-null    object 
 3   Dependents         357 non-null    object 
 4   Education          367 non-null    object 
 5   Self_Employed      344 non-null    object 
 6   ApplicantIncome    367 non-null    int64  
 7   CoapplicantIncome  367 non-null    int64  
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object 
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB


In [424]:
test.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [425]:
test['Credit_History'].mode()

0    1.0
Name: Credit_History, dtype: float64

In [426]:
test['Gender'].mode()

0    Male
Name: Gender, dtype: object

In [427]:
test['Dependents'].mode()

0    0
Name: Dependents, dtype: object

In [428]:
test['Self_Employed'].mode()

0    No
Name: Self_Employed, dtype: object

In [429]:
test['LoanAmount'].mean()

136.13259668508286

In [430]:
test['Loan_Amount_Term'].mean()

342.53739612188366

In [431]:
test['Credit_History'].fillna(1, inplace=True)
test['Self_Employed'].fillna('No', inplace=True)
test['LoanAmount'].fillna(136, inplace=True)
test['Dependents'].fillna('0', inplace=True)
test['Loan_Amount_Term'].fillna(342, inplace=True)
test['Gender'].fillna('Male', inplace=True)

In [432]:
test['Gender'] = label_encoder.fit_transform(test['Gender'])
test['Gender'].unique()

array([1, 0])

In [433]:
test['Credit_History'] = label_encoder.fit_transform(test['Credit_History'])
test['Credit_History'].unique()

array([1, 0], dtype=int64)

In [434]:
test['Self_Employed'] = label_encoder.fit_transform(test['Self_Employed'])
test['Self_Employed'].unique()

array([0, 1])

In [435]:
test['Dependents'] = label_encoder.fit_transform(test['Dependents'])
test['Dependents'].unique()

array([0, 1, 2, 3])

In [436]:
test['Property_Area'] = label_encoder.fit_transform(test['Property_Area'])
test['Property_Area'].unique()

array([2, 1, 0])

In [437]:
test['Education'] = label_encoder.fit_transform(test['Education'])
test['Education'].unique()

array([0, 1])

In [438]:
test['Married'] = label_encoder.fit_transform(test['Married'])
test['Married'].unique()

array([1, 0])

In [439]:
train = train.drop('Loan_ID',axis=1)
test = test.drop('Loan_ID',axis=1)

# EDA

In [440]:
X = train.drop('Loan_Status',axis=1)
y = train['Loan_Status']

In [441]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)

In [442]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(random_state=0)
dtree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [443]:
y_pred = dtree.predict(X_test)
print('Accuracy Score: ',round(accuracy_score(y_test, y_pred)*100,2),'%')

Accuracy Score:  66.67 %


In [444]:
accuracy_score(y_test,y_pred)

0.6666666666666666

In [445]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [446]:
pred_cv = model.predict(X_test)
accuracy_score(y_test,pred_cv)

0.8373983739837398

In [447]:
pred_test= model.predict(test)

In [448]:
submission=pd.read_csv(r"C:\Users\sreeh\Downloads\Submission.csv")

In [449]:
submission['Loan_Status']=pred_test 
test['Loan_ID']=submission['Loan_ID']

In [450]:
pd.DataFrame(submission, columns=['Loan_ID','Loan_Status']).to_csv('logistic.csv',index=False)